apiVersion: apps/v1
kind: Deployment
metadata:
  name: zap-challenge-deployment
  labels:
    app: zap-challenge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zap-challenge
  template:
    metadata:
      labels:
        app: zap-challenge
    spec:
      containers:
        - name: zap-challenge
          image: oliveiragustavo/zap-challenge:v2
          ports:
          - containerPort: 80